INSERT INTO PERSONA( PERSONA_NOMBRE, PERSONA_APELLIDO) VALUES('Hector', 'Fierro');
INSERT INTO PERSONA( PERSONA_NOMBRE, PERSONA_APELLIDO) VALUES('Juan', 'Perez');
INSERT INTO PERSONA( PERSONA_NOMBRE, PERSONA_APELLIDO) VALUES('Jhon', 'Doe');